require:
  - rubocop-performance

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_from:
  - .rubocop_todo.yml
  - node_modules/@prettier/plugin-ruby/rubocop.yml

inherit_mode:
  merge:
    - Exclude

Layout/LineLength:
  Exclude:
    - config/**/*.rb
    - db/**/*.rb
    - spec/lib/hmrc_interface/request/submission_spec.rb
    - spec/support/shared_contexts/hmrc_interface_stubs.rb

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Lint/AmbiguousBlockAssociation:
  AllowedMethods: [change]
