name: "Delete ECR images"
description: "Delete ECR images"
inputs:
  ecr-region:
    description: "ECR region"
    required: true
  ecr-url:
    description: "ECR endpoint url"
    required: true
  ecr-access-key-id:
    description: "AWS access key id for ECR"
    required: true
  ecr-secret-access-key:
    description: "AWS secret access key for ECR"
    required: true

runs:
  using: "composite"
  steps:
    - name: Delete ECR image
      shell: bash
      env:
        ECR_REGION: ${{ inputs.ecr-region }}
        ECR_URL: ${{ inputs.ecr-url }}
        AWS_ACCESS_KEY_ID: ${{ inputs.ecr-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.ecr-secret-access-key }}
      run: |
        echo "About to delete ECR images"
        bin/delete_ecr_images
