# Default values for assure-hmrc-data.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#
# DO NOT STORE SECRETS IN HERE!
#

replicaCount: 2

# image keys that need values provided by `helm install/upgrade...`
image:
  repository: null
  tag: null

service_account:
  name: laa-assure-hmrc-data-production-irsa

service:
  type: ClusterIP
  port: 80

ingress:
  className: modsec
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "assure-hmrc-data-laa-assure-hmrc-data-production-green"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/server-snippet: |
      # Block requests on weekends
      if ($date_gmt ~* "^(Sat|Sun)") {
        rewrite ^ /out-of-hours break;
      }

      # Block requests between 20:00 and 05:59 UTC (21:00 and 06:59 BST)
      if ($time_local ~ ":(2[0-3]|0[0-5]):") {
        rewrite ^ /out-of-hours break;
      }
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecAction "id:900110,phase:1,nolog,pass,t:none,setvar:tx.inbound_anomaly_score_threshold=6,setvar:tx.outbound_anomaly_score_threshold=4"
      SecRuleUpdateActionById 949110 "t:none,deny,status:423,logdata:%{SERVER_NAME}"
  hosts:
    - check-clients-details-using-hmrc-data.service.justice.gov.uk
  tls:
    - hosts:
      - domain: check-clients-details-using-hmrc-data.service.justice.gov.uk
        secretName: check-clients-details-using-hmrc-data-tls-certificate

branch_builder:
  enabled: false
  database_name: null
  omniauth_azure_redirect_uri: null

mock_azure:
  enabled: false

worker:
  replicaCount: 1

clamav:
  replicaCount: 1
  configFile: /etc/clamav/clamd.conf
  freshclamCheck: 24
  mirror: https://laa-clamav-mirror-production.apps.live.cloud-platform.service.justice.gov.uk

sidekiq:
  queue_name: null

host_env: production
