# Default values for assure-hmrc-data.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#
# DO NOT STORE SECRETS IN HERE!
#

replicaCount: 2

# image keys that need values provided by `helm install/upgrade...`
image:
  repository: null
  tag: null

service:
  type: ClusterIP
  port: 80

ingress:
  className: default
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "assure-hmrc-data-laa-assure-hmrc-data-staging-green"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
  hosts:
    - laa-assure-hmrc-data-staging.cloud-platform.service.justice.gov.uk
    - laa-assure-hmrc-data-staging.apps.live.cloud-platform.service.justice.gov.uk

resources:
  limits:
    cpu: 500m
    memory: 1G
  requests:
    cpu: 10m
    memory: 125Mi

postgresql:
  enabled: false
