# Default values for assure-hmrc-data.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#
# DO NOT STORE SECRETS IN HERE!
#

replicaCount: 1

# image key values must be set by `helm --set` command
image:
  repository: null
  tag: null

service:
  type: ClusterIP
  port: 80

# defaults overridden by branch builder
ingress:
  className: modsec
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "assure-hmrc-data-laa-assure-hmrc-data-uat-green"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecAction "id:900110,phase:1,nolog,pass,t:none,setvar:tx.inbound_anomaly_score_threshold=6,setvar:tx.outbound_anomaly_score_threshold=4"
      SecRuleUpdateActionById 949110 "t:none,deny,status:423,logdata:%{SERVER_NAME}"
  hosts: []

resources:
  limits:
    cpu: 500m
    memory: 1G
  requests:
    cpu: 10m
    memory: 125Mi

# database_name and redirect_uri value must be set by `helm --set` command when enabled
branch_builder:
  enabled: true
  database_name: null
  omniauth_azure_redirect_uri: null

mock_azure:
  enabled: true

worker:
  replicaCount: 1
