# Default values for assure-hmrc-data.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#
# DO NOT STORE SECRETS IN HERE!
#

replicaCount: 1

# image key values must be set by `helm --set` command
image:
  repository: null
  tag: null

service_account:
  name: laa-assure-hmrc-data-uat-irsa

service:
  type: ClusterIP
  port: 80

# defaults overridden by branch builder
ingress:
  className: modsec-non-prod
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "assure-hmrc-data-laa-assure-hmrc-data-uat-green"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecAction "id:900110,phase:1,nolog,pass,t:none,setvar:tx.inbound_anomaly_score_threshold=6,setvar:tx.outbound_anomaly_score_threshold=4"
      SecRuleUpdateActionById 949110 "t:none,deny,status:423,logdata:%{SERVER_NAME}"
      SecRule TIME_HOUR "!@pm 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22" \
        "id:998,phase:1,deny,status:503,tag:github_team=laa-apply-for-legal-aid"
      SecRule TIME_WDAY "^(6|7)$" \
        "id:999,phase:1,deny,status:503,tag:github_team=laa-apply-for-legal-aid"
  hosts: []

resources:
  limits:
    cpu: 500m
    memory: 1G
  requests:
    cpu: 10m
    memory: 125Mi

# database_name and redirect_uri value must be set by `helm --set` command when enabled
branch_builder:
  enabled: true
  database_name: null
  omniauth_azure_redirect_uri: null

mock_azure:
  enabled: true

worker:
  replicaCount: 1

clamav:
  replicaCount: 1
  configFile: /etc/clamav/clamd.conf
  freshclamCheck: 24
  mirror: https://laa-clamav-mirror-production.apps.live.cloud-platform.service.justice.gov.uk

host_env: uat

sidekiq:
  queue_name: null

customErrorService:
  enabled: true
