# WARNING: do not put typical sidekiq static queues configuration in here
#
# see docs/development/sidekiq_flows.md
#

:scheduler:
  :schedule:
    bulk_submissions_worker:
      cron: '0 21 * * *'
      class: BulkSubmissionsWorker
