---
# WARNING: do not put typical sidekiq static queues configuration in here
#
# see docs/flow.md
#

# TODO: alternative to applying dynamic queue names and concurrency per queue??
# see https://github.com/deanpcmad/sidekiq-limit_fetch !??
#
# TODO: alternative to applying dynamic queue names and concurrency per queue??
# use sidekiq's erb engine here!?? You cannot use `Rails` module methods here
# though as they are not loaded. :(
# EXAMPLE:
#
# :concurrency: 1
# :queues:
#   - <%= 'uc-one-' + ENV.fetch('APP_BRANCH', 'development') + '-submissions' %>
#   - <%= 'uc-two-' + ENV.fetch('APP_BRANCH', 'development') + '-submissions' %>

:scheduler:
  :schedule:
    bulk_submissions_worker:
      cron: '0 21 * * *'
      class: BulkSubmissionsWorker
