apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "assure-hmrc-data.fullname" . }}
  labels:
    {{- include "assure-hmrc-data.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  selector:
    matchLabels:
      {{- include "assure-hmrc-data.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "assure-hmrc-data.selectorLabels" . | nindent 8 }}
      annotations:
        releaseTime: {{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC"| quote }}
    spec:
      serviceAccountName: "{{ .Values.service_account.name }}"
      containers:
        - name: clamav
          image: ghcr.io/ministryofjustice/hmpps-clamav:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: clamav
              containerPort: 3310
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 3Gi
            requests:
              cpu: 10m
              memory: 1Gi
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
{{ include "assure-hmrc-data.envs" . | nindent 10 }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
