apiVersion: v1
kind: Service
metadata:
  name: {{ template "assure-hmrc-data.fullname" . }}-clamav
  labels:
    {{- include "assure-hmrc-data.labels" . | nindent 4 }}
    service: {{ template "assure-hmrc-data.fullname" . }}-clamav
spec:
  selector:
    service: {{ template "assure-hmrc-data.fullname" . }}-clamav
  clusterIP: None
  ports:
    - name: zombie-port # Actually, we do not use this port but it is still needed to allow the service to receive TCP traffic.
      port: 1234
      targetPort: 1234
