# This workflow integrates Brakeman with GitHub's Code Scanning feature
# Brakeman is a static analysis security vulnerability scanner for Ruby on Rails applications

name: Brakeman Scan

on:
  pull_request:
    branches: [main]

permissions: {}

jobs:
  brakeman:
    uses: ministryofjustice/laa-reusable-github-actions/.github/workflows/brakeman.yml@932ee576d65d9992ca82955a5823e3d55e888417 # main as of 28/07/2026
    permissions:
      contents: read # for actions/checkout
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
