name: Scan docker image
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

permissions: {}

jobs:
  scan-docker-image:
    uses: ministryofjustice/laa-reusable-github-actions/.github/workflows/snyk.yml@7c81d37978aef9418f7185d9ecf70e3cd1c63c02 # main on 15/04/2026
    permissions:
      actions: read
      contents: read
      security-events: write
    with:
      tag: "laa-assure-hmrc-data"
    secrets:
      snyk_token: ${{ secrets.SNYK_TOKEN }}
