name: CI and CD

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RACK_ENV: test
      RAILS_ENV: test
      DATABASE_URL: "postgresql://postgres:postgres@127.0.0.1/laa-assure-hmrc-data-test"

    services:
      postgres:
        image: postgres:14.5-alpine
        env:
          POSTGRES_DB: laa-assure-hmrc-data-test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.2.1'

      - name: Find yarn cache location
        id: yarn-cache
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: JS package cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install packages with yarn
        run: yarn install --frozen-lockfile

      - name: Precompile assets
        run: bin/rails assets:precompile

      - name: Setup test database
        run: bin/rails db:prepare

      - name: Run linters
        run: |
          bundle exec rubocop
          bundle exec rake erblint

      - name: Run tests
        run: bundle exec rspec

  build:
    if: github.actor != 'dependabot[bot]'
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Store current date
        run: echo "BUILD_DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Docker login to ECR
        env:
          ECR_REGION: ${{ secrets.ECR_AWS_DEFAULT_REGION }}
          ECR_URL: ${{ secrets.ECR_TEAM_REPO_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region ${ECR_REGION} | docker login --username AWS --password-stdin ${ECR_URL}

      - name: Build
        run: |
          docker build \
            --label build.git.sha=${{ github.sha }} \
            --label build.git.branch=${{ github.ref }} \
            --label build.date=${{ env.BUILD_DATE }} \
            --build-arg APP_BUILD_DATE=${{ env.BUILD_DATE }} \
            --build-arg APP_BUILD_TAG=${{ github.ref }} \
            --build-arg APP_GIT_COMMIT=${{ github.sha }} \
            --pull \
            --tag app .

      - name: Push to ECR
        env:
          ECR_URL: ${{ secrets.ECR_TEAM_REPO_URL }}
          GIT_SHA: ${{ github.sha }}
        run: |
          docker tag app "${ECR_URL}:${GIT_SHA}"
          docker push "${ECR_URL}:${GIT_SHA}"

          if [ ${{ github.ref }} == 'refs/heads/main' ]; then
            docker tag app "${ECR_URL}:latest"
            docker push "${ECR_URL}:latest"
          fi

  deploy-staging:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    environment: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to the cluster
        env:
          KUBE_CERT: ${{ secrets.KUBE_STAGING_CERT }}
          KUBE_TOKEN: ${{ secrets.KUBE_STAGING_TOKEN }}
          KUBE_CLUSTER: ${{ secrets.KUBE_STAGING_CLUSTER }}
          KUBE_NAMESPACE: ${{ secrets.KUBE_STAGING_NAMESPACE }}
        run: |
          echo "${KUBE_CERT}" > ca.crt
          kubectl config set-cluster ${KUBE_CLUSTER} --certificate-authority=./ca.crt --server=https://${KUBE_CLUSTER}
          kubectl config set-credentials deploy-user --token=${KUBE_TOKEN}
          kubectl config set-context ${KUBE_CLUSTER} --cluster=${KUBE_CLUSTER} --user=deploy-user --namespace=${KUBE_NAMESPACE}
          kubectl config use-context ${KUBE_CLUSTER}

      - name: Helm deployment to staging
        env:
          ECR_URL: ${{ secrets.ECR_TEAM_REPO_URL }}
          GIT_SHA: ${{ github.sha }}
          KUBE_NAMESPACE: ${{ secrets.KUBE_STAGING_NAMESPACE }}
          VALUES_FILE: .helm/assure-hmrc-data/values/staging.yaml
        run: |
          helm upgrade assure-hmrc-data .helm/assure-hmrc-data \
            --namespace ${KUBE_NAMESPACE} \
            --set image.repository="${ECR_URL}" \
            --set image.tag="${GIT_SHA}" \
            --values ${VALUES_FILE} \
            --install \
            --wait
